### ISSUE TITLE
trigger markers

### ISSUE THREAD

**Issue by simon-p-j-r** [Stardust-hyx/TabEAE#1]
Dear author, thanks for your open-code and fabulous artical.

seq_to_tabel.py文件中第153行：" dec_table_embeds[i, arg_slots] += (encoder_output[trigger_start-1] + encoder_output[trigger_end]) / 2"。是否应该是" dec_table_embeds[i, arg_slots] += (encoder_output[trigger_start] + encoder_output[trigger_end-1]) / 2"呢？

**Comment by Stardust-hyx** [comment]
Thanks for your attention on my work. As stated in the paper, the initial representation of argument slots is
the average of the encoding of corresponding arguement roles (in the column header) and the encoding
of corresponding **trigger markers**. Hence, the code here is correct.
